/*
 * File: app/view/MyPanel2.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BPMNEditor.view.MyPanel2', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.mypanel2',

    requires: [
        'BPMNEditor.view.MyPanel2ViewModel',
        'Ext.panel.Panel'
    ],

    viewModel: {
        type: 'mypanel2'
    },
    title: 'Activities',

    items: [
        {
            xtype: 'panel',
            title: 'Connectors'
        },
        {
            xtype: 'panel',
            title: 'Events'
        }
    ]

});