/*
 * File: app/view/bpmnPanel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BPMNEditor.view.bpmnPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.bpmnpanel',

    requires: [
        'BPMNEditor.view.bpmnPanelViewModel',
        'BPMNEditor.view.bpmnPanelViewController',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button'
    ],

    controller: 'bpmnpanel',
    viewModel: {
        type: 'bpmnpanel'
    },
    html: '<div id="pBPMN"></div>',
    id: 'pCanvas',
    title: 'BPMN project',

    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            items: [
                {
                    xtype: 'button',
                    action: 'btnNewDiagram',
                    itemId: 'mybutton',
                    text: 'New',
                    listeners: {
                        click: 'onMybuttonClick'
                    }
                },
                {
                    xtype: 'button',
                    text: 'Open'
                },
                {
                    xtype: 'button',
                    text: 'Save'
                },
                {
                    xtype: 'button',
                    text: 'Play'
                }
            ]
        }
    ]

});