/*
 * File: app/view/vpDiagram.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BPMNEditor.view.vpDiagram', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.vpdiagram',

    requires: [
        'BPMNEditor.view.vpDiagramViewModel',
        'BPMNEditor.view.pToolbox',
        'BPMNEditor.view.tpCanvas',
        'Ext.tab.Panel',
        'Ext.grid.Panel',
        'Ext.grid.View',
        'Ext.grid.column.Number'
    ],

    viewModel: {
        type: 'vpdiagram'
    },
    layout: 'border',

    items: [
        {
            xtype: 'panel',
            region: 'west',
            width: 150,
            layout: 'accordion',
            title: 'Toolbar',
            items: [
                {
                    xtype: 'ptoolbox'
                }
            ]
        },
        {
            xtype: 'tpcanvas',
            region: 'center'
        },
        {
            xtype: 'gridpanel',
            collapseMode: 'header',
            region: 'south',
            height: 50,
            animCollapse: true,
            collapsed: true,
            collapsible: true,
            title: 'Logs',
            columns: [
                {
                    xtype: 'gridcolumn',
                    weight: 1,
                    width: 720,
                    dataIndex: 'string',
                    text: 'Log'
                }
            ]
        },
        {
            xtype: 'gridpanel',
            region: 'east',
            width: 150,
            title: 'Properties',
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'string',
                    text: 'Property'
                },
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'number',
                    text: 'Value'
                }
            ]
        }
    ]

});