/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyViewport', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.myviewport',

    requires: [
        'MyApp.view.MyViewportViewModel',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.toolbar.Toolbar',
        'Ext.grid.Panel',
        'Ext.grid.View',
        'Ext.grid.column.Number'
    ],

    viewModel: {
        type: 'myviewport'
    },
    layout: 'border',

    items: [
        {
            xtype: 'panel',
            region: 'west',
            width: 150,
            layout: 'accordion',
            title: 'Toolbar',
            items: [
                {
                    xtype: 'panel',
                    title: 'Activities',
                    items: [
                        {
                            xtype: 'panel',
                            title: 'Connectors'
                        },
                        {
                            xtype: 'panel',
                            title: 'Events'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'tabpanel',
            region: 'center',
            activeTab: 0,
            items: [
                {
                    xtype: 'panel',
                    title: 'BPMN project',
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'button',
                                    text: 'New'
                                },
                                {
                                    xtype: 'button',
                                    text: 'Open'
                                },
                                {
                                    xtype: 'button',
                                    text: 'Save'
                                },
                                {
                                    xtype: 'button',
                                    text: 'Play'
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'gridpanel',
            collapseMode: 'header',
            region: 'south',
            height: 50,
            animCollapse: true,
            collapsed: true,
            collapsible: true,
            title: 'Logs',
            columns: [
                {
                    xtype: 'gridcolumn',
                    weight: 1,
                    width: 720,
                    dataIndex: 'string',
                    text: 'Log'
                }
            ]
        },
        {
            xtype: 'gridpanel',
            region: 'east',
            width: 150,
            title: 'Properties',
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'string',
                    text: 'Property'
                },
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'number',
                    text: 'Value'
                }
            ]
        }
    ]

});